apiVersion: v1
kind: Service
metadata:
  name: bun-k8s-demo
  labels:
    app: bun-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: bun-k8s-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
